name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup the SDK required version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build App
        run: dotnet build  -c Release --no-restore

      - name: Run Automated Tests
        run: dotnet test -c Release --no-build
